# Generated by Django 4.2.7 on 2026-04-24 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('category', models.CharField(choices=[('Food & Dining', 'Food & Dining'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Entertainment', 'Entertainment'), ('Health & Fitness', 'Health & Fitness'), ('Bills & Utilities', 'Bills & Utilities'), ('Travel', 'Travel'), ('Education', 'Education'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
